// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPovGMml_-iePCOKjanJdiyEMXy4knoLc',
    appId: '1:476353985862:android:2ea7f2ddb94a2f3d16b947',
    messagingSenderId: '476353985862',
    projectId: 'frutflix-4bf41',
    storageBucket: 'frutflix-4bf41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFse4SyB5Z6VUIREFzmkTV3qwp0tzVfhQ',
    appId: '1:476353985862:ios:b16b4ee101ca8e8016b947',
    messagingSenderId: '476353985862',
    projectId: 'frutflix-4bf41',
    storageBucket: 'frutflix-4bf41.appspot.com',
    iosClientId: '476353985862-viiu6418r5fi7u5akd6dj2vlfh83gsjl.apps.googleusercontent.com',
    iosBundleId: 'frutflix',
  );
}
